version: 2
jobs:
  test:
    docker:
    - image: elixir:latest
    steps:
    - checkout
    - run: mix local.rebar --force
    - run: mix local.hex --force
    - run: mix deps.get
    - run: mix test

workflows:
  version: 2
  build_and_test:
    jobs:
    - test
